language: python

python:
  - "3.5"

os:
  - linux
  - osx

before_install:
  - mkdir -p $HOME/bin
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -O https://github.com/git-lfs/git-lfs/releases/download/v2.2.0/git-lfs-darwin-amd64-2.2.0.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/github/git-lfs/releases/download/v2.2.0/git-lfs-linux-amd64-2.2.0.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar xvfz git-lfs-darwin-amd64-2.2.0.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xvfz git-lfs-linux-amd64-2.2.0.tar.gz; fi
  - mv git-lfs-2.2.0/git-lfs $HOME/bin/git-lfs
  - export PATH=$PATH:$HOME/bin/

install:
  - pipenv install

script: py.test
