language: python
python:
  - "3.5"
before_install:
  - mkdir -p $HOME/bin
  - wget https://github.com/github/git-lfs/releases/download/v2.2.0/git-lfs-linux-amd64-2.2.0.tar.gz
  - tar xvfz git-lfs-linux-amd64-2.2.0.tar.gz
  - mv git-lfs-2.2.0/git-lfs $HOME/bin/git-lfs
  - export PATH=$PATH:$HOME/bin/
install:
  - pipenv install
script: py.test
